version: '3.8'

services:
  checkout-db:
    image: postgres:15
    container_name: checkout-db
    environment:
      POSTGRES_DB: checkout_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - checkout_db_data:/var/lib/postgresql/data
    networks:
      - checkout-network

  checkout-service:
    build: .
    container_name: checkout-service
    environment:
      - PORT=3003
      - DB_HOST=checkout-db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=checkout_db
      - JWT_SECRET=your-secret-key
      - USERS_SERVICE_URL=http://host.docker.internal:3000
      - PRODUCTS_SERVICE_URL=http://host.docker.internal:3001
      - RABBITMQ_URL=amqp://admin:admin@host.docker.internal:5672
      - RABBITMQ_MANAGEMENT_URL=http://host.docker.internal:15672
    ports:
      - "3003:3003"
    depends_on:
      - checkout-db
    networks:
      - checkout-network

volumes:
  checkout_db_data:

networks:
  checkout-network:
    driver: bridge